-- ============================================================
-- 05_share_links.sql
-- Creates the share_links table and its indexes.
--
-- Security notes:
--   • public_token is a cryptographically random 16-byte value
--     stored as 32 hex characters. Generated by the application
--     using crypto.randomBytes(16).toString('hex').
--   • password_hash is a bcrypt hash (cost 12) when the share is
--     password-protected. Never stored in plaintext.
--   • expires_at and max_downloads enforce access limits.
--     The application checks both before serving any download.
-- ============================================================

USE LeekuSecure;
GO

CREATE TABLE share_links (
    id             UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    file_id        UNIQUEIDENTIFIER NOT NULL,

    -- Cryptographically random 16-byte token encoded as 32 hex chars
    public_token   CHAR(32)         NOT NULL,

    -- bcrypt hash (cost 12) of the optional share password
    password_hash  NVARCHAR(256)    NULL,

    expires_at     DATETIMEOFFSET   NULL,
    max_downloads  INT              NULL,
    download_count INT              NOT NULL DEFAULT 0,
    is_active      BIT              NOT NULL DEFAULT 1,
    created_at     DATETIMEOFFSET   NOT NULL DEFAULT SYSDATETIMEOFFSET(),

    CONSTRAINT PK_share_links       PRIMARY KEY CLUSTERED (id),
    CONSTRAINT UQ_share_links_token UNIQUE (public_token),
    CONSTRAINT FK_share_links_files FOREIGN KEY (file_id)
                                    REFERENCES files(id) ON DELETE CASCADE,
    CONSTRAINT CK_share_links_dl    CHECK (max_downloads IS NULL OR max_downloads > 0)
);
GO

CREATE NONCLUSTERED INDEX IX_share_links_file_id
    ON share_links (file_id)
    INCLUDE (is_active, public_token);
GO

PRINT '05_share_links.sql completed.';
GO
